### ISSUE TITLE
Mirror Camera

### ISSUE THREAD

**Issue by idnovic** [benjones/presenterMode#1]
Hi,

thank you for creating this.

I tested the lastest beta version.
Can you please add a vertical mirror settings for the camera feed?
The default feed from my camera is not mirrored. 
This is confusing because I can see the window (real window, air) in real life on my left 
and in the feed it is also on the left.
This is wrong for me because I see myself mirrored on my screen.

I point with a finder to the left and the screen shows me pointing to the right.
I want to mirror my camera feed to make it work like a real life mirror basically.

Thank you!

**Comment by benjones** [comment]
Glad this is useful for people who don't sit down the hall from me!

I think I know how to do that technically (like, I think I know what APIs I'd use).  Since I assume that's not something everyone wants, at least not as a default, I'm not sure I know what a good UI for that feature would be, especially since it would only be for camera devices, but not ios devices (which are handled the same way in my app).  Any suggestions?

**Comment by idnovic** [comment]
Here is what I have found out:

Photo Booth mirrors by default without exposing a setting. 

QuickTime does not mirror by default without exposing a setting. 

Screencast mirrors by default without exposing a setting. 

Camouflage Studio does not mirror by default. Setting is in menubar under "Framing - Mirror Video"

IShowU does not mirror by default without exposing a setting.

Suggestion:

Menubar
File - New Mirror window Window
Window - Window Picker
Window - Mirror Window
View - Camera - Mirror

UI
Mark active Devices as active and open the Mirror window instead of recreating them. 
Add a reload button to active devices to recreate them. 
Add a mirror button to active devices to mirror the feed and show the status of the mirror.

**Comment by benjones** [comment]
What do you think of the latest alpha release?  UI seems simple enough

**Comment by idnovic** [comment]
Looks good to me.
I updated to the sequoia beta today and needed to figure out how to allow your app first.
Seems like we need to go to settings - privacy and security - allow app.

Thank you!

**Comment by benjones** [comment]
I never knew there was a way to allow the apps without that whole awful process.  Thanks for the suggestion!

**Comment by idnovic** [comment]
I think this is new in sequoia.
It used to be cmd + right click - open - open anyway
or
terminal ....

I did not try to allow the app in the terminal.
But the settings app worked.
